### ISSUE TITLE
Unable to configure windows service with spaces

### ISSUE THREAD

**Issue by bloodmc** [chef/win32-service#53]
## Description
Unable to configure windows service with name `ORACLE ProcMGR V12.2.2.0.0_VS2015`. Error received is `The parameter is incorrect. - ChangeServiceConfig: The parameter is incorrect.`

## Gem Version
win32-service 1.0.1

## Windows Version
Windows Server 2016

## Replication Case
```ruby
        Service.configure(
          :service_name       => "ORACLE ProcMGR V12.2.2.0.0_VS2015",
          :service_start_name => "TestUser",
          :password           => "TEST",
        )
```

**Comment by bloodmc** [comment]
Seems to be an issue with how oracle is creating the service. Usually the service name should contain no spaces or special characters but in this case it does. I tested with `sc.exe` and had same error so closing as this is not an issue with win32.

**Comment by mrswadge** [comment]
I'm having an issue with configure not applying the change also. It says all the right things, but when it comes down to it, it's not altering anything.

```
sbschef-node02   * windows_service[Application NodeManager (D_OT_WebLogic_12c_wlserver)] action configure[2019-01-30T14:15:36+00:00] INFO: Processing windows_service[Application NodeManager (D_OT_WebLogic_12c_wlserver)] action configure (otbo_domain::distribute line 192)
sbschef-node02 C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-1.0.1/lib/win32/service.rb:1086:in `rescue in block in services' : WARNING: Failed to retrieve description for the CDPUserSvc_1206c375 service. (StructuredWarnings::StandardWarning
sbschef-node02 )
sbschef-node02 C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-1.0.1/lib/win32/service.rb:1099:in `rescue in block in services' : WARNING: Unable to get delayed auto start information for the CDPUserSvc_1206c375 service (StructuredWarnings::StandardWarning)C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-1.0.1/lib/win32/service.rb:1157:in `rescue in block in services' : WARNING: Unable to retrieve failure actions for the CDPUserSvc_1206c375 service (StructuredWarnings::StandardWarning)
sbschef-node02
sbschef-node02     - update Application NodeManager (D_OT_WebLogic_12c_wlserver)
sbschef-node02     -   set run_as_user to ".\\Administrator" (was "LocalSystem")
sbschef-node02   * windows_service[Application NodeManager (D_OT_WebLogic_12c_wlserver)] action restart[2019-01-30T14:15:36+00:00] INFO: Processing windows_service[Application NodeManager (D_OT_WebLogic_12c_wlserver)] action restart (otbo_domain::distribute line 198)
sbschef-node02 C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-1.0.1/lib/win32/service.rb:1086:in `rescue in block in services' : WARNING: Failed to retrieve description for the CDPUserSvc_1206c375 service. (StructuredWarnings::StandardWarning
sbschef-node02 )C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-1.0.1/lib/win32/service.rb:1099:in `rescue in block in services' : WARNING: Unable to get delayed auto start information for the CDPUserSvc_1206c375 service (StructuredWarnings::StandardWarning)C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-1.0.1/lib/win32/service.rb:1157:in `rescue in block in services' : WARNING: Unable to retrieve failure actions for the CDPUserSvc_1206c375 service (StructuredWarnings::StandardWarning)
sbschef-node02 [2019-01-30T14:15:37+00:00] INFO: windows_service[Application NodeManager (D_OT_WebLogic_12c_wlserver)] configured.
sbschef-node02 [2019-01-30T14:15:38+00:00] INFO: windows_service[Application NodeManager (D_OT_WebLogic_12c_wlserver)] restarted
sbschef-node02
sbschef-node02     - restart service windows_service[Application NodeManager (D_OT_WebLogic_12c_wlserver)]
```

When I check the service, the run as username is still LocalSystem???

It appears to work for my other scenario where the service is named "Application develop_AdminServer". So I'm not sure if it is the spaces in my instance.
